%
% FILE NAME:    masterScriptWormGEM.m
%
%
% PURPOSE: This script is for reconstruction of the Worm-GEM, by using
%          the Human-GEM as template and taking into account worm-specific
%          pathways/reactions.
%
%          Annotation files in tsv format are also generated by
%          integrating human and worm-specific annotation information.
%


%% Add path
addpath(genpath('../../Worm-GEM/'));


%% Prepare Worm ortholog pairs and species-specific network

% get ortholog pairs from human to worm
wormOrthologPairs = extractAllianceGenomeOrthologs('human2WormOrthologs.json');

% load species-specific rxns and mets
rxnsToAdd = importTsvFile('wormSpecificRxns.tsv');
metsToAdd = importTsvFile('wormSpecificMets.tsv');


%% Generate Worm-GEM
[wormGEM, speciesSpecNetwork, gapfillNetwork]=updateAnimalGEM(...
    wormOrthologPairs,rxnsToAdd,metsToAdd,'Worm-GEM');


%% Update annotation files
[rxnAssoc, metAssoc] = updateAnimalAnnotations(wormGEM,rxnsToAdd,metsToAdd);


%% Save annotation into tsv files, and the model into mat, yml, and xml

% sanity check
if isequal(rxnAssoc.rxns, wormGEM.rxns) && isequal(metAssoc.mets, wormGEM.mets)
	fprintf('sanity check passed.\n');
    exportTsvFile(rxnAssoc,'../model/reactions.tsv');
    exportTsvFile(metAssoc,'../model/metabolites.tsv');
end

save('../model/Worm-GEM.mat', 'wormGEM');
writeYaml(wormGEM, '../model/Worm-GEM.yml');
exportModel(wormGEM, '../model/Worm-GEM.xml');

